services:
  # MongoDB Database
  mongo:
    image: mongo:6
    container_name: varms-mongo
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  # Mongo Express - Web UI for MongoDB
  mongo-express:
    image: mongo-express:1.0.2-20
    container_name: varms-mongo-express
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin

  # NestJS Backend
  backend:
    build:
      context: ./varms-backend
      dockerfile: Dockerfile
    container_name: varms-backend
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    command: npm run start:dev
    volumes:
      - ./varms-backend:/usr/src/app
      # - /usr/src/app/node_modules

  # Next.js Frontend
  frontend:
    build:
      context: ./varms-frontend
      dockerfile: Dockerfile
    container_name: varms-frontend
    restart: always
    env_file:
      - .env
    ports:
      - "3001:3000"
    depends_on:
      - backend
    command: npm run dev
    volumes:
      - ./varms-frontend:/usr/src/app
      # - /usr/src/app/node_modules

volumes:
  mongo_data:
